# GitLab CI/CD configuration for Ruby gem
image: ruby:3.4.1

# Variables
variables:
  DEBIAN_FRONTEND: noninteractive
  BUNDLE_PATH: cache

# Cache gems between builds
cache: &global_cache
  paths:
    - cache
  policy: pull-push

# Define stages
stages:
  - test
  - build
  - deploy

# Before script - install dependencies
before_script:
  - ruby -v
  - which ruby
  - gem install bundler --no-document
  - bundle version
  - bundle install --jobs $(nproc)

# Test stage
rspec:
  stage: test
  script:
    - bundle exec rspec
  #coverage: '/\(\d+\.\d+\%\) covered/'
  #artifacts:
    #reports:
      #coverage_report:
        #coverage_format: cobertura
        #path: coverage/coverage.xml
    #paths:
      #- coverage/
    #expire_in: 30 days
  only:
    - branches
    - merge_requests

## Code quality with RuboCop
#rubocop:
  #stage: test
  #script:
    #- bundle exec rubocop --format json --out rubocop-report.json
  #artifacts:
    #reports:
      #codequality: rubocop-report.json
    #paths:
      #- rubocop-report.json
    #expire_in: 30 days
  #only:
    #- branches
    #- merge_requests

## Build gem
#build_gem:
  #stage: build
  #cache:
    #<<: *global_cache
    #policy: pull
  #script:
    #- bundle exec rake build
  #artifacts:
    #paths:
      #- pkg/*.gem
    #expire_in: 1 week
  #rules:
    #- if: $CI_PIPELINE_SOURCE == "merge_request_event"
      #when: never
    #- if: $CI_COMMIT_REF_NAME == "main"
    #- if: $CI_COMMIT_TAG

## Test gem installation
#test_gem_install:
  #stage: build
  #cache:
    #<<: *global_cache
    #policy: pull
  #dependencies:
    #- build_gem
  #script:
    #- gem install pkg/*.gem
    #- ruby -e "require 'llm_conductor'; puts 'Gem loaded successfully'"
  #rules:
    #- if: $CI_PIPELINE_SOURCE == "merge_request_event"
      #when: never
    #- if: $CI_COMMIT_REF_NAME == "main"
    #- if: $CI_COMMIT_TAG

## Deploy to RubyGems (only on tags)
## deploy_rubygems:
##   stage: deploy
##   cache:
##     <<: *global_cache
##     policy: pull
##   dependencies:
##     - build_gem
##   script:
##     - mkdir -p ~/.gem
##     - echo ":rubygems_api_key: ${RUBYGEMS_API_KEY}" > ~/.gem/credentials
##     - chmod 600 ~/.gem/credentials
##     - gem push pkg/*.gem
##   rules:
##     - if: $CI_COMMIT_TAG
##       when: manual
##   environment:
##     name: production
##     url: https://rubygems.org/gems/llm_conductor
