plugins:
  - rubocop-rspec

# Don't inherit Rails configuration from parent since this is a standalone Ruby gem
inherit_from: ~

AllCops:
  TargetRubyVersion: 3.1
  NewCops: disable

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/HashSyntax:
  EnforcedShorthandSyntax: always

# Explicitly disable Rails cops since this is a standalone Ruby gem
Rails/Blank:
  Enabled: false

Rails/Present:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Metrics/MethodLength:
  Max: 15

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/UnspecifiedException:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/DescribeMethod:
  Enabled: false

Style/Documentation:
  Enabled: false

# Configuration complete above 