# RuboCop configuration for GitLab CI
require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4.1
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'pkg/**/*'
    - 'spec/spec_helper.rb'

# GitLab CI specific - generate JSON report
Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Layout/LineLength:
  Max: 120